blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='blog'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'), 
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('category/<slug:slug>/', views.CategoriesView.as_view(), name='category-list'),
]

kevinpwhite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap, PortfolioSiteMap, StaticSitemap
from .views import error_404, error_500

admin.site.site_header = "Kevin P White's Admin Portal"

sitemaps = {
    'static': StaticSitemap,
    'portfolio': PortfolioSiteMap,
    'blog': PostSitemap,
    }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404
handler500 = error_500

portfolio/urls.py
from django.urls import path
from . import views

app_name='portfolio'
urlpatterns = [
    path('', views.PortfolioListView.as_view(), name='portfolio'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'), 
    path('<slug:slug>/', views.PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('category/<slug:slug>/', views.CategoriesView.as_view(), name='category-list'),
]

portfolio/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "Portfolio Category"

    def __str__(self):
        return self.name

class Portfolio(models.Model):
    title = models.CharField(max_length=200)
    images = models.ImageField(upload_to='images/portfolio')
    content = CKEditor5Field('Content', config_name='default', null=True)
    slug = models.SlugField(max_length=200, default="")
    category = models.ForeignKey('Category', related_name='category', on_delete=models.CASCADE)
    
    class Meta: 
        verbose_name_plural = "Portfolio"
    
    #Display Portfolio Title on Admin Panel
    def __str__(self):
        return self.title

class PortfolioImage(models.Model):
    post = models.ForeignKey('Portfolio', related_name='portfolioimages', on_delete=models.CASCADE)
    images = models.FileField(upload_to='images/portfolio', null=True)
    images_alt_tag = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.post.title
        

portfolio/views.py
from .models import Category, Portfolio
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.contrib.postgres.search import SearchVector

app_name='portfolio'

class SearchResultsView(ListView):
    model = Portfolio
    template_name = 'portfolio/search.html'
    context_object_name = 'portfoliosearch_list'
    paginate_by = 12

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Portfolio.objects.annotate(search=SearchVector('title', 'content')).filter(search=query)
        return Portfolio.objects.none()
    
    
    
# Create your views here.    
class PortfolioListView(ListView):
    model = Portfolio
    context_object_name ='portfolios'
    paginate_by = 9
    ordering = ['title']

    def get_context_data(self, **kwargs):
        context = super(PortfolioListView, self).get_context_data(**kwargs)
        context['categories_list'] = Category.objects.all()
        return context

class PortfolioDetailView(DetailView):
    model = Portfolio

    def get_context_data(self, **kwargs):
        #brings in the Portfolio model as self
        context = super(PortfolioDetailView,self).get_context_data(**kwargs)
        # filters portfolio model with the self cat id assigned
        catset = Portfolio.objects.all()
        # variable that stores queryset values for image and slug
        context['category_set'] = catset
        return context

class CategoriesView(ListView):
    model=Portfolio
    template_name='portfolio/category_list.html'
    context_object_name='categories'
    paginate_by = 6

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Portfolio.objects.filter(category=self.category)  

    def get_context_data(self, **kwargs):
        context = super(CategoriesView, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context

portfolio/templates/portfolio/base_list.html
<a class="relative block mb-8 lg:mb-0 rounded-lg shadow-2xl hover:scale-105 ease-in-out duration-1000" href="{% url 'portfolio:portfolio-detail' portfolio.slug %}">
  <div class="block rounded-lg bg-white text-white shadow-secondary-1 dark:bg-surface-dark">
    <img class="rounded-lg" src="{{ portfolio.images.url }}" alt="{{ portfolio.images.alt }}" />
    <!-- Dark overlay -->
    <div class="absolute inset-0 bg-black opacity-20 rounded-lg"></div>
    <div class="absolute top-0 p-6">
        <h5 class="mb-2 text-xl font-medium leading-tight text-white">
          {{portfolio.title}}
        </h5>
    </div>
  </div>
</a>

portfolio/templates/portfolio/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="animate__animated animate__fadeInUp container mx-auto p-8 lg:px-20">
  <h1 class="text-center text-4xl my-6">{{ category }}</h1>
  {% if object_list %}
    <div class="mx-auto lg:grid lg:grid-cols-3 lg:gap-8">
      {% for portfolio in categories %}
        {% include 'portfolio/base_list.html' %}
      {% endfor %}
    </div>{% comment %}----------end grid {% endcomment %}
  {% else %}
    <div class="mx-auto min-h-screen">
      <h6 class="text-center text-2xl">Sorry, nothing has been posted yet!</h6>
    </div>
  {% endif %}
  {% include 'pagination.html' %}
</div>{% comment %}---------end container {% endcomment %}
{% endblock %}

portfolio/templates/portfolio/portfolio_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% comment %} ----------------offcanvas start-------------------- {% endcomment %}
<div class="animate__animated animate__fadeInUp flex-grow pt-4 overflow-y-auto small min-h-screen container mx-auto p-8 lg:px-20">
        <div class="bg-white">
          <div class="rounded-lg mx-auto w-full lg:h-96 overflow-hidden shadow-2xl">
            <img class="w-full h-full object-cover object-center rounded-lg" src="{{ portfolio.images.url }}" alt="{{ portfolio.title }}" />
          </div>           
          <div class="ckeditor py-6 justify-start">
              <h1 class="text-4xl mb-4">{{ portfolio.title }}</h1>
              {{portfolio.content | safe }}
            <div id="carouselExampleCaptions" class="carousel slide relative" data-bs-ride="carousel">
              <div class="carousel-inner relative w-full overflow-hidden">
                {% for portfolioimage in portfolio.portfolioimages.all %}
                  <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %} relative float-left w-full">
                    <div class="rounded-lg shadow-2xl relative overflow-hidden bg-no-repeat bg-cover" style="background-position: 50%;">
                      <img src="{{portfolioimage.images.url}}" alt="{{portfolioimage.images_alt_tag}}" class="block w-full" />
                      <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed bg-black opacity-25"></div>
                    </div>
                    <div class="carousel-caption hidden md:block absolute text-center">
                      <h3 class="text-4xl">{{portfolioimage.images_alt_tag}}</h3>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>{% comment %} ----------------end of slider{% endcomment %}        
          </div>
        </div>
      </div>
</div>{% comment %} ----------------offcanvas end{% endcomment %}  

{% endblock %}

portfolio/templates/portfolio/portfolio_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="animate__animated animate__fadeInUp mx-auto overflow-hidde container mx-auto p-8 lg:px-20">
    <h1 class="text-center text-4xl my-5">My Portfolio</h1>
    <div class="flex justify-center">
      <div class="w-full">
        <form method="GET" action="{% url 'portfolio:search-results' %}">
          <div class="input-group relative flex flex-wrap items-stretch w-full mb-4">
              <input type="search" name="q" class="form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-sky-600 focus:outline-none" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
              <button class="btn inline-block px-6 py-2.5 bg-sky-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-sky-500 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 transition duration-300 ease-in-out flex items-center" type="submit" id="button-addon2">
                  <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="w-4" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                      <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                  </svg>
              </button>
          </div>
        </form>      
      </div>
    </div>
      <ul class="nav nav-pills nav-justified flex flex-col md:flex-row flex-wrap list-none pl-0 mb-4" id="pills-tab" role="tablist">
        {% if object_list %}
        {% else %}
        <div class="mx-auto min-h-screen">
          <h6 class="text-center text-2xl">Sorry, nothing has been posted yet!</h6>
        </div>
        {% endif %}
        {% for category in categories_list %}
        <li class="hover:scale-105 ease-in-out duration-1000 nav-item flex-grow text-center my-2 whitespace-nowrap" role="presentation">
          <a href="{% url 'portfolio:category-list' category.slug %}" class="
            nav-link
            block
            font-medium
            text-xs
            leading-tight
            uppercase
            rounded
            px-6
            py-3
            lg:my-2
            md:mr-2
            hover:text-white
            hover:bg-sky-600 
            focus:outline-none focus:ring-0
            drop-shadow-md
            transition duration-300 ease-in-out
          ">{{ category }}</a>
        </li>
        {% endfor %}
      </ul>

      <section class="mx-auto my-6 lg:grid lg:grid-cols-3 lg:gap-8">
        {% for portfolio in portfolios %}
          {% include 'portfolio/base_list.html' %}
        {% endfor %}
      </section>

      {% include 'pagination.html' %}
    </div>

{% endblock %}

portfolio/templates/portfolio/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="animate__animated animate__fadeInUp container mx-auto p-8 lg:px-20">
    <h1 class="text-center text-4xl my-5">Search Results</h1>
    <div>
        {% if portfoliosearch_list %}
            <section class="lg:grid lg:grid-cols-3 lg:gap-8">
                {% for portfolio in portfoliosearch_list %}
                    {% include 'portfolio/base_list.html' %}
                {% endfor %}
            </section>
        {% else %}
            <h6 class="text-center text-2xl">No results found for your search.</h6>
        {% endif %}
    </div>
    {% include 'pagination.html' %}
</div>
{% endblock %}