blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='blog'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'), 
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('category/<slug:slug>/', views.CategoriesView.as_view(), name='category-list'),
]

kevinpwhite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap, PortfolioSiteMap, StaticSitemap
from .views import error_404, error_500

admin.site.site_header = "Kevin P White's Admin Portal"

sitemaps = {
    'static': StaticSitemap,
    'portfolio': PortfolioSiteMap,
    'blog': PostSitemap,
    }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404
handler500 = error_500

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field
from mptt.models import MPTTModel, TreeForeignKey

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)
class Post(models.Model):
    category = TreeForeignKey('PostCategory', null=True, on_delete=models.CASCADE, related_name='postcategory')
    title = models.CharField(max_length=200, unique=True)
    featured_image = models.ImageField(upload_to='images/blog', null=True)
    featured_img_alt_tag = models.CharField(max_length=200, null=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE, related_name='blog_posts')
    updated_on = models.DateField(auto_now= True)
    content = CKEditor5Field('Content', config_name='default', null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        verbose_name_plural = "Post"
        ordering = ('-created_on',)

    def __str__(self):
        return self.title


class PostCategory(MPTTModel):
    category = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        unique_together = (('parent', 'slug',))
        verbose_name_plural = 'Post Categories'

    def __str__(self):
        return self.category

class PostImage(models.Model):
    post = models.ForeignKey('Post', related_name='postimages', on_delete=models.CASCADE)
    images = models.FileField(upload_to='images/blog', null=True)
    images_alt_tag = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.post.title    

blog/views.py
from .models import Post, PostCategory
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.contrib.postgres.search import SearchVector

app_name='blog'

class SearchResultsView(ListView):
    model = Post
    template_name = 'blog/search.html'
    context_object_name = 'postsearch_list'
    paginate_by = 12

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Post.objects.annotate(search=SearchVector('title', 'content')).filter(search=query)
        return Post.objects.none()
    
# Create your views here.    
class PostListView(ListView):
    model = Post
    context_object_name='posts'
    paginate_by = 6

    def get_queryset(self):
        return Post.objects.filter(status=1)

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['categories_list'] = PostCategory.objects.all()
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'  # Ensure you specify the correct template

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Fetch the post object from the context
        post = self.object
        # Add the category to the context
        context['category'] = post.category  # Access the category directly from the post
        return context

class CategoriesView(ListView):
    model = Post
    template_name = 'blog/category_list.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        # Get the selected category based on the slug passed in the URL
        self.category = get_object_or_404(PostCategory, slug=self.kwargs['slug'])
        
        # Fetch all posts in this category and its child categories
        descendants = self.category.get_descendants(include_self=True)
        return Post.objects.filter(category__in=descendants)  

    def get_context_data(self, **kwargs):
        context = super(CategoriesView, self).get_context_data(**kwargs)
        
        # Include the category in the context so you can display it in the template
        context['category'] = self.category
        
        # Optionally include child categories to display them
        context['child_categories'] = self.category.get_children()
        
        return context

blog/templates/blog/base_list.html
<a class="relative block mb-8 lg:mb-0 overflow-hidden rounded-lg shadow-2xl border border-gray-100 p-4 hover:scale-105 ease-in-out duration-1000" href="{% url 'blog:post-detail' post.slug %}">
  <div class="block shrink-0">
    <img alt="" src="{{ post.featured_image.url }}" class="rounded-lg object-cover shadow-sm h-40 w-full" />
  </div>

  <span class="absolute inset-x-0 -bottom-0 h-2 bg-gradient-to-r from-gray-900 via-sky-600 to-gray-900"></span>
  
  <div class="sm:flex sm:justify-between sm:gap-2">
    <div>
      <h3 class="text-lg text-sky-600 sm:text-xl mt-2">{{ post.title }}</h3>
    </div>
  </div>

  <div class="text-pretty text-black text-sm">
    {{ post.content|safe|truncatewords:30}}
  </div>

  <dl class="mt-6 flex gap-4 sm:gap-6">
    <div class="flex flex-col-reverse">
      <span class="text-sm font-medium text-gray-500">
        Updated On: {{ post.updated_on|date:'M. d, Y' }}
      </span>
      <span class="text-sm font-medium text-gray-500">
        Author: {{ post.author|default:"Unknown Author" }}
      </span>
    </div>
  </dl>
</a>

blog/templates/blog/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="animate__animated animate__fadeInUp container mx-auto p-8 lg:px-20">
  <h1 class="text-center text-4xl my-6">{{ category.category }}</h1>

  {% if child_categories %}
    <ul class="flex justify-center mb-6">
      {% for child in child_categories %}
        <li class="mx-4">
          <a href="{% url 'blog:category-list' child.slug %}" class="text-blue-500 hover:underline">
            Subcategories: {{ child.category }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}

  {% if posts %}
  <section class="mx-auto lg:grid lg:grid-cols-3 lg:gap-8">
    {% for post in posts %}
      {% include 'blog/base_list.html' %}
    {% endfor %}
  </section>
  
  {% else %}
    <div class="mx-auto min-h-screen">
      <h6 class="text-center text-2xl">Sorry, nothing has been posted yet!</h6>
    </div>
  {% endif %}

  {% include 'pagination.html' %}
</div>{% comment %}---------end container {% endcomment %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="animate__animated animate__fadeInUp container mx-auto p-8 lg:px-20">
  <h1 class="text-center text-4xl my-5">Blog</h1>
  
  <div class="flex justify-center">
    <div class="w-full">
      <form method="GET" action="{% url 'blog:search-results' %}">
        <div class="input-group relative flex flex-wrap items-stretch w-full mb-4">
            <input type="search" name="q" class="form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-sky-600 focus:outline-none" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
            <button class="btn inline-block px-6 py-2.5 bg-sky-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-sky-500 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 transition duration-300 ease-in-out flex items-center" type="submit" id="button-addon2">
                <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="w-4" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                </svg>
            </button>
        </div>
      </form>
    
    </div>
  </div>

  <ul class="nav nav-pills nav-justified flex flex-col md:flex-row flex-wrap list-none pl-0 mb-4" id="pills-tab" role="tablist">
    {% if object_list %}
    {% else %}
    <div class="mx-auto min-h-screen">
      <h6 class="text-center text-2xl">Sorry, nothing has been posted yet!</h6>
    </div>
    {% endif %}
    
    {% for category in categories_list %}
    <li class="hover:scale-105 ease-in-out duration-1000 nav-item flex-grow text-center my-2 md:mr-2 whitespace-nowrap" role="presentation">
      <a href="{% url 'blog:category-list' category.slug %}" class="
        nav-link
        block
        font-medium
        text-xs
        leading-tight
        uppercase
        rounded
        px-6
        py-3
        lg:my-2
        md:mr-2
        hover:text-white
        hover:bg-sky-600 
        focus:outline-none focus:ring-0
        drop-shadow-md
        transition duration-300 ease-in-out
      ">{{ category }}</a>
    </li>
    {% endfor %}
  </ul>

  <section class="mx-auto lg:grid lg:grid-cols-3 lg:gap-8">
    {% for post in posts %}
      {% include 'blog/base_list.html' %}
    {% endfor %}
  </section>

  {% include 'pagination.html' %}
</div>

{% endblock %}

blog/templates/blog/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="animate__animated animate__fadeInUp container mx-auto p-8 lg:px-20">
    <h1 class="text-center text-4xl my-5">Search Results</h1>
    <div>
        {% if postsearch_list %}
            <section class="lg:grid lg:grid-cols-3 lg:gap-8">
                {% for post in postsearch_list %}
                    {% include 'blog/base_list.html' %}
                {% endfor %}
            </section>
        {% else %}
            <h6 class="text-center text-2xl">No results found for your search.</h6>
        {% endif %}
    </div>
    {% include 'pagination.html' %}
</div>
{% endblock %}